export default [
  {
    id: 3493,
    model: {
      id: 295,
      name: "Voxy",
      make: {
        id: 5,
        name: "Toyota",
      },
    },
    created_at: "2024-02-20T20:27:00.188883Z",
    updated_at: "2024-02-20T20:29:02.232859Z",
    name: "Toyota Voxy KIRAMEKI 11 2.0L",
    description:
      "AUCTION STOCK!! ON AUCTION\r\nSATURDAY 24TH FEBRUARY 2024!\r\nGRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\n2000cc petrol engine, automatic transmission, four wheel drive, fabric seats, dual zone climate controls, Infotainment system display screen, powered doors, reverse camera, push-start ignition, Antilock braking system, and foglamps.",
    price_currency: "KES",
    price: "2629999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Van",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 65000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "112500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0084.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 193,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 151,
      acceleration: 10,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: false,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "toyota-voxy-kirameki-11-20l-plfgawt",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3492,
    model: {
      id: 98,
      name: "Levorg",
      make: {
        id: 8,
        name: "Subaru",
      },
    },
    created_at: "2024-02-20T20:19:26.053727Z",
    updated_at: "2024-02-20T20:21:58.165927Z",
    name: "Subaru Levorg 1.6L Turbo AWD",
    description:
      "AUCTION STOCK!! ON AUCTION\r\nFRIDAY 23RD FEBRUARY 2024!\r\nGRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nSymmetrical all wheel drive setup, keyless entry, two tone fabric seats, electric parking brake, Multifunctional steering wheel, reverse camera, auto start-stop for fuel efficiency, auto headlights, Anti-collision brake assist, and alloy rims.",
    price_currency: "KES",
    price: "2470000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Station Wagon",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 25000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "90000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0232.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 250,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 1600,
      horse_power: 168,
      acceleration: 8.7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 14,
      fuel_tank_capacity: null,
      highway_consumption: 16,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "subaru-levorg-16l-turbo-awd-cezwpw1",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3491,
    model: {
      id: 29,
      name: "A5",
      make: {
        id: 1,
        name: "Audi",
      },
    },
    created_at: "2024-02-20T20:12:52.644370Z",
    updated_at: "2024-02-20T20:14:28.615162Z",
    name: 'Audi A5 "B9" S-Line 2.0T QUATTRO/SUNROOF',
    description:
      "AUCTION STOCK!! ON AUCTION THURSDAY 22ND FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2018\r\n\r\nMultifunctional steering wheel, half leather S-Line sport seats, adaptive headlights, virtual instrument cluster, sunroof, premium surround sound system, dual zone climate controls, and traction control.",
    price_currency: "KES",
    price: "4599999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Saloon",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 25000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "180000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0222.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Premium Surround System",
      massage_seats: false,
      power_windows: true,
      seat_material: "Semi Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Audi MM1 infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: true,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 370,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 252,
      acceleration: 7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: true,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 11,
      fuel_tank_capacity: null,
      highway_consumption: 13,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "audi-a5-b9-s-line-20t-quattrosunroof-csm3lta",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3490,
    model: {
      id: 31,
      name: "A7",
      make: {
        id: 1,
        name: "Audi",
      },
    },
    created_at: "2024-02-20T20:07:07.865592Z",
    updated_at: "2024-02-20T20:08:44.985796Z",
    name: "Audi A7 2.0T S-LINE SPORTBACK QUATTRO",
    description:
      "AUCTION STOCK!! ON AUCTION THURSDAY 22ND FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nQuattro All wheel drive, powered leather seats with memory function, heated seats, Multifunctional steering wheel, engine immobilizer, all round parking sensors, hill hold assist, radar guided adaptive cruise control, and Bluetooth connectivity.",
    price_currency: "KES",
    price: "4450000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Saloon",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 36000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "180000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0217.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Premium Surround System",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Audi MM1 infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 370,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 252,
      acceleration: 6,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: true,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 11,
      fuel_tank_capacity: null,
      highway_consumption: 13,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "audi-a7-20t-s-line-sportback-quattro-j1x3gne",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3489,
    model: {
      id: 54,
      name: "GLE350",
      make: {
        id: 3,
        name: "Mercedes",
      },
    },
    created_at: "2024-02-20T20:02:04.241313Z",
    updated_at: "2024-02-20T20:03:41.774427Z",
    name: "Mercedes Benz GLE 350d COUPE AMG-LINE/SUNROOF",
    description:
      "AUCTION STOCK!! ON AUCTION WEDNESDAY 21ST FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nPowered Nappa leather seats, heated seats, Mercedes speedtronic cruise control, Mercedes Comand Infotainment system, premium surround sound system, panoramic sunroof, Downhill speed regulation, active parking assist system, ambient lighting, multiple climate zones, smartphone integration, and Anti theft alarm.",
    price_currency: "KES",
    price: "9450000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 63000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "405000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0207.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Premium Surround System",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Mercedes Command infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 620,
      cylinders: 6,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 3000,
      horse_power: 255,
      acceleration: 5,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 9,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: true,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 11,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mercedes-benz-gle-350d-coupe-amg-linesunroof-bvfd12u",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3488,
    model: {
      id: 50,
      name: "S400",
      make: {
        id: 3,
        name: "Mercedes",
      },
    },
    created_at: "2024-02-20T19:55:52.572587Z",
    updated_at: "2024-02-20T19:57:32.556961Z",
    name: "Mercedes Benz S400 HYBRID AMG LINE",
    description:
      'AUCTION STOCK!! ON AUCTION WEDNESDAY 21ST FEBRUARY 2024! GRADE 4B\r\n\r\nRegistration: 2017\r\n\r\nPowered leather seats with memory functionality, 4-zone climate controls, Multifunctional steering wheel, interior wood trimming, push-start ignition, 12.3" infotainment display screen, auto start-stop functionality, Burmester premium surround sound system, Ambient lighting, and All round parking sensors.',
    price_currency: "KES",
    price: "6648000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Saloon",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 88000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "297000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0205.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Burmester",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Multi Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Mercedes Command infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 400,
      cylinders: 6,
      fuel_type: "Petrol Hybrid",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 3500,
      horse_power: 330,
      acceleration: 5,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 9,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: true,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 11,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mercedes-benz-s400-hybrid-amg-line-w7hoa8h",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3487,
    model: {
      id: 87,
      name: "Lx570",
      make: {
        id: 9,
        name: "Lexus",
      },
    },
    created_at: "2024-02-20T19:50:10.600981Z",
    updated_at: "2024-02-20T19:51:55.497075Z",
    name: "Lexus LX570/SUNROOF",
    description:
      "AUCTION STOCK!! ON AUCTION FRIDAY 23RD FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nPowered leather seats with heating function, Multifunctional steering wheel, wireless phone charging functionality, multizone climate controls, Mark Levinson Premium surround sound system, roof rails, hill start & descent assist, smartphone integration, storage coolbox, rear mounted spoiler, and terrain response management system.",
    price_currency: "KES",
    price: "13880000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 28000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "585000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0193.jpg",
    interior_features: {
      sunroof: true,
      cool_box: true,
      trimming: "Wood",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Mark levinson",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Multi Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Touchscreen Infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 530,
      cylinders: 8,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 5700,
      horse_power: 383,
      acceleration: 7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 9,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 6,
      fuel_tank_capacity: null,
      highway_consumption: 8,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "lexus-lx570sunroof-o7zsywh",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3486,
    model: {
      id: 219,
      name: "E220",
      make: {
        id: 3,
        name: "Mercedes",
      },
    },
    created_at: "2024-02-20T19:43:22.218507Z",
    updated_at: "2024-02-20T19:45:15.656642Z",
    name: "Mercedes Benz E220d AMG-LINE/SUNROOF",
    description:
      "AUCTION STOCK!! ON AUCTION THURSDAY 22ND FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nBucket-styled two tone leather seats, daytime running LED lights, dual zone climate controls, panoramic sunroof, side mirror indicators, push start ignition, premium surround sound system, Mercedes speedtronic cruise control, reverse camera, and tyre pressure monitoring system.",
    price_currency: "KES",
    price: "5235000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Saloon",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "2WD",
    mileage: 34000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "225000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0187.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Premium Surround System",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Mercedes Command infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 360,
      cylinders: 4,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 150,
      acceleration: 7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 12,
      fuel_tank_capacity: null,
      highway_consumption: 14,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mercedes-benz-e220d-amg-linesunroof-vmrcfug",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3485,
    model: {
      id: 163,
      name: "Cayenne",
      make: {
        id: 6,
        name: "Porsche",
      },
    },
    created_at: "2024-02-20T19:35:42.245875Z",
    updated_at: "2024-02-20T19:37:52.429360Z",
    name: 'Porsche Cayenne "GTS" 3.6L BITURBO V6 / AIR SUSPENSION',
    description:
      "IMPORT READY STOCK!! NON-AUCTION STOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; 8-speed automatic transmission, powered red leather seats, daytime running LED lights, BOSE premium surround sound system, air suspension setup, heated seats, dual zone climate controls, analog cabin clock, metallic paddle shifters, cruise control, panoramic sunroof, engine immobilizer, hill descent assist, and Porsche Traction Management system.",
    price_currency: "KES",
    price: "10915000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "United Kingdom",
    drive: "AWD",
    mileage: 54000,
    mileage_unit: "Miles",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "450000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0184.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Bose",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Porsche PCM infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 603,
      cylinders: 6,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 3600,
      horse_power: 440,
      acceleration: 4.5,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 8,
      fuel_tank_capacity: null,
      highway_consumption: 10,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Very Good",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "porsche-cayenne-gts-36l-biturbo-v6-air-suspension-ew6qzic",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3484,
    model: {
      id: 163,
      name: "Cayenne",
      make: {
        id: 6,
        name: "Porsche",
      },
    },
    created_at: "2024-02-20T19:27:17.817753Z",
    updated_at: "2024-02-20T19:29:09.326164Z",
    name: "Porsche Cayenne 3.0 V6 'Typ 92A' / PANORAMIC SUNROOF",
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; 3.0L turbocharged diesel engine, heated steering wheel, multiple way electrically adjustable front seats, panoramic sunroof, memory seats package, heated seats, Porsche Communication Management System, BOSE premium surround sound system, dual front & side mounted curtain airbags, and keyless entry.",
    price_currency: "KES",
    price: "8668350.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "United Kingdom",
    drive: "AWD",
    mileage: 46000,
    mileage_unit: "Miles",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "382500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0135.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Bose",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Porsche PCM infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 580,
      cylinders: 6,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 3000,
      horse_power: 258,
      acceleration: 6,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 10,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "porsche-cayenne-30-v6-typ-92a-panoramic-sunroof-tochm9p",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3483,
    model: {
      id: 38,
      name: "Harrier",
      make: {
        id: 5,
        name: "Toyota",
      },
    },
    created_at: "2024-02-20T19:16:20.891491Z",
    updated_at: "2024-02-20T19:18:11.789222Z",
    name: "Toyota Harrier Premium Advanced Package",
    description:
      "AUCTION STOCK!! ON AUCTION 22ND FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\nInterior wood trim, dual zone climate controls, Multifunctional steering wheel, push start ignition, rear mounted spoiler, and front & side mounted airbags.",
    price_currency: "KES",
    price: "3685000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 59000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "157500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0129.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Wood",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 185,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 155,
      acceleration: 9,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: false,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "toyota-harrier-premium-advanced-package-9ukiym6",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3482,
    model: {
      id: 106,
      name: "Xtrail",
      make: {
        id: 14,
        name: "Nissan",
      },
    },
    created_at: "2024-02-20T19:08:12.693940Z",
    updated_at: "2024-02-20T19:09:34.481116Z",
    name: 'Nissan XTRAIL  "NT32"',
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; Leather seats, flat bottomed steering wheel, leather seats, Infotainment system control screen, sunroof, daytime running lights, Multifunctional steering wheel, dual zone climate controls, and traction control.",
    price_currency: "KES",
    price: "2799999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 31000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "112500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0122.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 240,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 180,
      acceleration: 10,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "nissan-xtrail-nt32-l6e0ax4",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3481,
    model: {
      id: 19,
      name: "Cx3",
      make: {
        id: 4,
        name: "Mazda",
      },
    },
    created_at: "2024-02-20T19:01:50.047127Z",
    updated_at: "2024-02-20T19:03:01.053439Z",
    name: "Mazda CX-3 1.5D XD PROACTIVE",
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; Front wheel drive, Infotainment system control screen with Mazda connect system, fabric seats, Multifunctional tilt & telescopic steering wheel, push-start ignition, cruise control, dual zone climate control, and rear mounted spoiler.",
    price_currency: "KES",
    price: "2119243.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "2WD",
    mileage: 35000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "90000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0117.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 270,
      cylinders: 4,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 1500,
      horse_power: 103,
      acceleration: 8,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 15,
      fuel_tank_capacity: null,
      highway_consumption: 17,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mazda-cx-3-15d-xd-proactive-iacn6au",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3480,
    model: {
      id: 220,
      name: "Landcruiser",
      make: {
        id: 5,
        name: "Toyota",
      },
    },
    created_at: "2024-02-20T18:54:11.094409Z",
    updated_at: "2024-02-20T18:58:38.549706Z",
    name: "Toyota Landcruiser Prado TZ-G GDJ151",
    description:
      "AUCTION STOCK!! ON AUCTION FRIDAY 23RD FEBRUARY 2024! GRADE 4.5A\r\n\r\nRegistration: 2018\r\n\r\nLeather seats, side steps, multi-terrain select system, multizone climate controls, heated seats, cooled front seats, adaptive cruise control, active height control, Adjustable ride height, front & side impact curtain airbags, sunroof, 7 seater, CRAWL mode for offroading, and traction control.",
    price_currency: "KES",
    price: "9550000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 25000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "405000.00",
    year_of_manufacture: 2018,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0113.jpg",
    interior_features: {
      sunroof: true,
      cool_box: true,
      trimming: "Wood",
      cooled_seats: true,
      heated_seats: true,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 7,
      air_conditioning: "Multi Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: true,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 450,
      cylinders: 4,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2800,
      horse_power: 184,
      acceleration: 7.5,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 11,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "toyota-landcruiser-prado-tz-g-gdj151-nibzop7",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3479,
    model: {
      id: 169,
      name: "FJ Cruiser",
      make: {
        id: 5,
        name: "Toyota",
      },
    },
    created_at: "2024-02-20T18:49:17.508685Z",
    updated_at: "2024-02-20T18:50:34.035901Z",
    name: "Toyota FJ CRUISER 4WD OFFROAD PACKAGE",
    description:
      "AUCTION STOCK!! ON AUCTION THURSDAY 22ND FEBRUARY 2024! GRADE 4.5B\r\n\r\nRegistration: 2017\r\n\r\n5 Speed automatic transmission, cloth/fabric seats, side steps, Multifunctional steering wheel, reverse camera, fog lights, front & side impact curtain airbags, 5 seater, and keyless entry.",
    price_currency: "KES",
    price: "5500000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 38000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "225000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0106.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: false,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: false,
    },
    engine_specifications: {
      torque: 380,
      cylinders: 6,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 4000,
      horse_power: 276,
      acceleration: 8,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: false,
      parking_sensors: false,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: false,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 8,
      fuel_tank_capacity: null,
      highway_consumption: 10,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "toyota-fj-cruiser-4wd-offroad-package-djtpsrh",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3478,
    model: {
      id: 154,
      name: "Forester XT",
      make: {
        id: 8,
        name: "Subaru",
      },
    },
    created_at: "2024-02-20T18:43:13.484568Z",
    updated_at: "2024-02-20T18:44:30.597536Z",
    name: "Subaru Forester XT",
    description:
      "IMPORT READY STOCK!! NON-AUCTION STOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; Automatic transmission, Eyesight adaptive cruise control, symmetrical AWD setup, paddle shifters, keyless entry, half leather seats, electric parking brake, Multifunctional steering wheel, Auto start stop for fuel efficiency, and Anti-collision brake assist.",
    price_currency: "KES",
    price: "3485000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 28000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "135000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0092.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Semi Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 350,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 250,
      acceleration: 8,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 11,
      fuel_tank_capacity: null,
      highway_consumption: 13,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "subaru-forester-xt-ntm6fgw",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3477,
    model: {
      id: 83,
      name: "Tiguan",
      make: {
        id: 11,
        name: "Volkswagen",
      },
    },
    created_at: "2024-02-20T13:07:30.121793Z",
    updated_at: "2024-02-20T13:10:20.943030Z",
    name: "Volkswagen Tiguan 2.0T",
    description:
      "The 2.0L 4MOTION Tiguan is not an absolute thriller but it is still very interesting to drive. Volkswagen created an absolute balance of performance and convenience with the engine producing 200hp and 320Nm of torque handling a 5 seater car capable of offroading as indicated by the offroad select mode!",
    price_currency: "KES",
    price: "1649999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Kenyan Used",
    current_location: "Nairobi, Kenya.",
    drive: "AWD",
    mileage: 179000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "67500.00",
    year_of_manufacture: 2012,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0059.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: false,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: false,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 320,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 200,
      acceleration: 8,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "sell_on_behalf",
    purchase_status: "Available",
    condition: "Very Good",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: null,
    is_published: true,
    slug: "volkswagen-tiguan-14t-vsxogxz",
    agent_whatsapp_contact: "+254737665566",
    uploaded_by: 10,
  },
  {
    id: 3476,
    model: {
      id: 20,
      name: "Axela",
      make: {
        id: 4,
        name: "Mazda",
      },
    },
    created_at: "2024-02-20T12:50:50.478468Z",
    updated_at: "2024-02-20T12:52:49.753129Z",
    name: "Mazda Axela 1.5L",
    description:
      "The Axela has a lot of pros that come with its small 1.5L petrol engine that has relatively good output with torque of 144Nm, enough boot space and legroom for the car's occupants, excellent reliability, and versatility. You can't think of any other hatch from those in its class with these features.",
    price_currency: "KES",
    price: "1749999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Hatchback",
    source: "Kenyan Used",
    current_location: "Nairobi, Kenya.",
    drive: "2WD",
    mileage: 49800,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "76500.00",
    year_of_manufacture: 2016,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240220-WA0030.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 144,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 1500,
      horse_power: 109,
      acceleration: 9,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: false,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 14,
      fuel_tank_capacity: null,
      highway_consumption: 16,
    },
    availability: "sell_on_behalf",
    purchase_status: "Available",
    condition: "Very Good",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: null,
    is_published: true,
    slug: "mazda-axela-15l-gqwejaw",
    agent_whatsapp_contact: "+254737665566",
    uploaded_by: 10,
  },
  {
    id: 3475,
    model: {
      id: 19,
      name: "Cx3",
      make: {
        id: 4,
        name: "Mazda",
      },
    },
    created_at: "2024-02-19T20:52:55.717198Z",
    updated_at: "2024-02-19T20:54:28.996936Z",
    name: "Mazda CX-3 2.0L",
    description:
      "IMPORT READY STOCK!! NON-AUCTION STOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; 6 speed automatic transmission, front wheel drive, Infotainment system control screen with Mazda Connect system, leather seats, Multifunctional tilt and telescopic steering wheel, push-start ignition, cruise control, dual zone climate controls, keyless entry, and rear mounted spoiler.",
    price_currency: "KES",
    price: "2625000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "2WD",
    mileage: 46000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "112500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0298.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 206,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 154,
      acceleration: 9,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 7,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: false,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mazda-cx-3-20l-lvef6cf",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3474,
    model: {
      id: 18,
      name: "Cx5",
      make: {
        id: 4,
        name: "Mazda",
      },
    },
    created_at: "2024-02-19T20:29:44.441331Z",
    updated_at: "2024-02-19T20:30:49.336735Z",
    name: "Mazda CX-5 2.2D AWD",
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; 6 Speed automatic transmission, all wheel drive, Infotainment system control screen, daytime running lights, leather seats, Multifunctional tilt and telescopic steering wheel, Premium surround sound system, Push-start ignition, cruise control, dual zone climate controls, side impact airbags, and Adaptive front light system.",
    price_currency: "KES",
    price: "2999999.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 88000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "135000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0281.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 420,
      cylinders: 4,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2200,
      horse_power: 190,
      acceleration: 7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 12,
      fuel_tank_capacity: null,
      highway_consumption: 14,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "mazda-cx-5-22d-awd-5fedv7g",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3473,
    model: {
      id: 67,
      name: "X5",
      make: {
        id: 2,
        name: "Bmw",
      },
    },
    created_at: "2024-02-19T20:22:40.085802Z",
    updated_at: "2024-02-19T20:25:25.910628Z",
    name: 'BMW X5 XDRIVE 35d "F15" M-SPORT',
    description:
      "The BMW X5 XDrive 35d F15 generation is the third generation of the X5 that was produced between 2013 and 2018. The G05 was produced from 2019 onwards to the present. The F15 listed has powered leather seats, adaptive headlights, Harman Kardon Premium surround sound system, Merino tan leather interior, Adaptive LED headlights with high beam assist, powered seats, and traction control.",
    price_currency: "KES",
    price: "6732290.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 58000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "292500.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0270.jpg",
    interior_features: {
      sunroof: true,
      cool_box: false,
      trimming: "Wood",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Harman Kardon",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "BMW idrive infotainment",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 560,
      cylinders: 6,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 3000,
      horse_power: 255,
      acceleration: 7,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: true,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 11,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "bmw-x5-xdrive-35d-f15-m-sport-y9dhf0i",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3472,
    model: {
      id: 93,
      name: "Forester",
      make: {
        id: 8,
        name: "Subaru",
      },
    },
    created_at: "2024-02-19T20:15:41.976678Z",
    updated_at: "2024-02-19T20:17:29.560296Z",
    name: 'Subaru Forester "SJ5" AWD S-LIMITED',
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS;Automatic transmission, Eyesight adaptive cruise control, symmetrical AWD setup, paddle shifters, keyless entry, fabric seats, electric parking brake, Multifunctional steering wheel, Auto start stop for fuel efficiency, and Anti-collision brake assist.",
    price_currency: "KES",
    price: "3477000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 19000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "135000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0262.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 196,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 146,
      acceleration: 8,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 10,
      fuel_tank_capacity: null,
      highway_consumption: 12,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "subaru-forester-sj5-awd-s-limited-cynzu4l",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3471,
    model: {
      id: 83,
      name: "Tiguan",
      make: {
        id: 11,
        name: "Volkswagen",
      },
    },
    created_at: "2024-02-19T20:02:32.826865Z",
    updated_at: "2024-02-19T20:09:09.867963Z",
    name: "Volkswagen Tiguan 1.4T",
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration: 2017\r\n\r\nSPECIFICATIONS; Fabric seats, Dynaudio premium surround sound system, flat bottomed multifunctional steering wheel, digital instrument cluster, side impact airbags, rear mounted spoiler, parking sensors, adaptive cruise control with lane & Blindspot monitoring assist, and engine immobilizer.",
    price_currency: "KES",
    price: "3600000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "2WD",
    mileage: 52000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "135000.00",
    year_of_manufacture: 2017,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0236.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Premium Surround System",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "Dual Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: true,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 250,
      cylinders: 4,
      fuel_type: "Petrol",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 1400,
      horse_power: 148,
      acceleration: 9,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: true,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 14,
      fuel_tank_capacity: null,
      highway_consumption: 16,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "volkswagen-tiguan-14t-9anmrzh",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3470,
    model: {
      id: 273,
      name: "XV",
      make: {
        id: 8,
        name: "Subaru",
      },
    },
    created_at: "2024-02-19T19:54:21.334867Z",
    updated_at: "2024-02-19T19:58:01.518557Z",
    name: "SUBARU XV HYBRID",
    description:
      "IMPORT READY STOCK!! NON-AUCTION\r\nSTOCK!\r\n\r\nRegistration:2019\r\n\r\nSPECIFICATIONS;2.0L hybrid petrol engine, Eyesight adaptive cruise control, symmetrical AWD setup, paddle shifters, keyless entry, fabric seats, electric parking brake, all round parking sensors, and Anti-collision brake assist.",
    price_currency: "KES",
    price: "3518302.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "Hatchback",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "AWD",
    mileage: 40000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "135000.00",
    year_of_manufacture: 2019,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0225.jpg",
    interior_features: {
      sunroof: false,
      cool_box: false,
      trimming: "Polished Metal",
      cooled_seats: false,
      heated_seats: false,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Fabric",
      number_of_seats: 5,
      air_conditioning: "",
      powered_tailgate: false,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: true,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: true,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 196,
      cylinders: 4,
      fuel_type: "Petrol Hybrid",
      aspiration: "Natural",
      speed_unit: "Km/hr",
      engine_size: 2000,
      horse_power: 148,
      acceleration: 9,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: false,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: false,
      adaptive_cruise_control: true,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: true,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 11,
      fuel_tank_capacity: null,
      highway_consumption: 13,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "subaru-xv-hybrid-t0e8vvj",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
  {
    id: 3469,
    model: {
      id: 220,
      name: "Landcruiser",
      make: {
        id: 5,
        name: "Toyota",
      },
    },
    created_at: "2024-02-19T19:48:16.459844Z",
    updated_at: "2024-02-19T19:50:08.181944Z",
    name: 'Toyota Landcruiser TZ-G "GDJ151"',
    description:
      "AUCTION STOCK!! ON AUCTION FRIDAY 23RD FEBRUARY 2024! GRADE 4.5A\r\n\r\nRegistration: 2021\r\n\r\nLeather seats, side steps, multi-terrain select system, multizone climate controls, heated seats, Adjustable ride height, front & side impact curtain airbags, sunroof, 7 seater, CRAWL mode for offroading, and traction control.",
    price_currency: "KES",
    price: "11300000.00",
    global_market_price_currency: "USD",
    global_market_price: null,
    body_type: "SUV",
    source: "Foreign Used",
    current_location: "Japan",
    drive: "4WD",
    mileage: 16000,
    mileage_unit: "KM",
    color: null,
    annual_insurance_currency: "KES",
    annual_insurance: "495000.00",
    year_of_manufacture: 2021,
    thumbnail:
      "https://dashboard.kaiandkaro.com/media/vehicles/thumbnails/IMG-20240219-WA0214.jpg",
    interior_features: {
      sunroof: true,
      cool_box: true,
      trimming: "Wood",
      cooled_seats: false,
      heated_seats: true,
      sound_system: "Factory Sound system",
      massage_seats: false,
      power_windows: true,
      seat_material: "Leather",
      number_of_seats: 7,
      air_conditioning: "Multi Zone",
      powered_tailgate: true,
      soft_close_doors: false,
      steering_controls: true,
      third_row_seating: false,
      phone_connectivity: true,
      rear_entertainment: false,
      auto_start_and_stop: false,
      infotainment_system: "Android Auto",
      cigarette_lighter_port: false,
      isofix_child_seat_anchors: true,
      digital_instrument_cluster: false,
      steering_mounted_paddle_shifts: false,
      apple_car_play_and_android_auto: true,
      fm_radio_with_bluetooth_aux_and_usb: true,
      keyless_entry_and_push_button_start: true,
    },
    engine_specifications: {
      torque: 450,
      cylinders: 4,
      fuel_type: "Diesel",
      aspiration: "Turbo/Supercharger",
      speed_unit: "Km/hr",
      engine_size: 2800,
      horse_power: 184,
      acceleration: 7.5,
      self_driving: false,
      self_parking: false,
      transmission: "Automatic",
    },
    safety_features: {
      gps_tracker: true,
      night_vision: false,
      srs_air_bags: true,
      reverse_camera: true,
      head_up_display: false,
      lane_assistance: true,
      parking_sensors: true,
      tow_hitch_assist: false,
      number_of_airbags: 8,
      hill_descent_control: true,
      road_sign_recognition: false,
      roll_stability_control: false,
      standard_cruise_contol: true,
      adaptive_cruise_control: false,
      antilock_braking_system: true,
      emergency_braking_assist: true,
      blind_spot_warning_assist: false,
      immobilizer_and_anti_theft: true,
      automatic_brake_hold_system: false,
      electronic_stability_control: false,
      tyre_pressure_monitoring_system: true,
      electronic_brakeforce_distribution: true,
    },
    fuel_consumption: {
      fuel_unit: "Litre",
      urban_consumption: 9,
      fuel_tank_capacity: null,
      highway_consumption: 11,
    },
    availability: "direct_import_stock",
    purchase_status: "Available",
    condition: "Excellent",
    duty_and_clearance_fee_currency: "USD",
    duty_and_clearance_fee: null,
    estimated_arrival_days: 45,
    is_published: true,
    slug: "toyota-landcruiser-tz-g-gdj151-gu9a7sa",
    agent_whatsapp_contact: "+254716770077",
    uploaded_by: 10,
  },
];
